### PR TITLE
My updates for Bedrock-v409

### PR DESCRIPTION
**Pull request by bundabrg**
## Overview

List of updates for Bedrock Protocol v409

## Todo
* [X] CreativeContentPacket
* [X] CraftingDataPacket
* [ ] MoveEntityDeltaPacket

### CODE REVIEW

**Comment by SupremeMortal** [comment]
409 is outdated now. We're on 411 if I recall correctly. 
I think an alternative fix for the blocking needs to be done because it's not guaranteed to be the same ID on a specific version. Depends on what the server sends in the item palette.

**Comment by bundabrg** [comment]
That will mean some state will need to be kept in Protocol or something provided during deserializing which sounds a bit awkwards.

My beta's are 409 so I must have an out of date beta on my devices.

**Comment by bundabrg** [comment]
Closing as its probably not worth tracking betas until rc status.

**Comment by SupremeMortal** [comment]
It's probably better that you move the 409 protocol to 411 since we don't plan on supporting betas after they are outdated.

**Pull request closed without merging**
